//{{NO_DEPENDENCIES}}
// Microsoft eMbedded Visual C++ generated include file.
// Used by TestApp.rc
//
#define IDOK2                           3
#define IDCLEAR                         3
#define IDD_DIALOG_DATE_TIME            101
#define IDD_TESTAPP_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_KEYPAD               129
#define IDD_DIALOG_CONFIG               130
#define IDD_DIALOG_KEYPAD_ALPHA         133
#define IDC_BUTTON_0                    1000
#define IDC_BUTTON_1                    1001
#define IDC_BUTTON_CONFIG_1             1001
#define IDC_BUTTON_2                    1002
#define IDC_EDIT_NAME                   1002
#define IDC_BUTTON_CONFIG_7             1002
#define IDC_BUTTON_6                    1003
#define IDC_EDIT_OFFSET                 1003
#define IDC_BUTTON_CONFIG_2             1003
#define IDC_BUTTON_9                    1004
#define IDC_COMBO_READ_WRITE            1004
#define IDC_BUTTON_CONFIG_8             1004
#define IDC_BUTTON_3                    1005
#define IDC_COMBO_BITS                  1005
#define IDC_EDIT_CONFIG_1_STATIC        1005
#define IDC_BUTTON_4                    1006
#define IDC_EDIT_READ_WRITE_CONFIG1     1006
#define IDC_BUTTON_5                    1007
#define IDC_BUTTON_START_CONFIG1        1007
#define IDC_EDIT_CONFIG_7_STATIC        1007
#define IDC_BUTTON_7                    1008
#define IDC_BUTTON_ENTER_CONFIG1        1008
#define IDC_BUTTON_WRITE_WINDOW1        1008
#define IDC_BUTTON_8                    1009
#define IDC_BUTTON_START_UPDATE_DISPLAY 1009
#define IDC_EDIT_READ_WRITE_CONFIG7     1009
#define IDC_BUTTON1_DECIMAL             1010
#define IDC_BUTTON_STOP_UPDATE_DISPLAY  1010
#define IDC_BUTTON_WRITE_WINDOW7        1010
#define IDC_BUTTON_CAL                  1011
#define IDC_BUTTON_MINUS                1011
#define IDC_BUTTON_KEYPAD               1012
#define IDC_BUTTON_START_WRITE_DISK_THREAD 1012
#define ID_CLEAR                        1013
#define IDC_BUTTON_STOP_WRITE_DISK_THREAD 1013
#define IDC_EDIT_CONFIG_2_STATIC        1014
#define IDC_BUTTON_A                    1014
#define IDC_EDIT_READ_WRITE_CONFIG2     1015
#define IDC_BUTTON_A2                   1015
#define IDC_BUTTON_B                    1015
#define IDC_BUTTON_WRITE_WINDOW2        1016
#define IDC_BUTTON_A3                   1016
#define IDC_BUTTON_C                    1016
#define IDC_LIST_READ_WRITE             1016
#define IDC_BUTTON_A4                   1017
#define IDC_BUTTON_D                    1017
#define IDC_EDIT_CONFIG_8_STATIC        1017
#define IDC_BUTTON_A5                   1018
#define IDC_BUTTON_E                    1018
#define IDC_LIST_BITS                   1018
#define IDC_EDIT_READ_WRITE_CONFIG8     1018
#define IDC_BUTTON_A6                   1019
#define IDC_BUTTON_F                    1019
#define IDC_BUTTON_SAVE_CONFIGURATION   1019
#define IDC_BUTTON_A7                   1020
#define IDC_BUTTON_G                    1020
#define IDC_BUTTON_START_DATA_COLLECTION 1020
#define IDC_BUTTON_HEX                  1020
#define IDC_BUTTON_A8                   1021
#define IDC_BUTTON_H                    1021
#define IDC_BUTTON_STOP_DATA_COLLECTION 1021
#define IDC_BUTTON_A9                   1022
#define IDC_BUTTON_Q                    1022
#define IDC_BUTTON_WRITE_WINDOW8        1022
#define IDC_BUTTON_A10                  1023
#define IDC_BUTTON_R                    1023
#define IDC_EDIT_TIME                   1023
#define IDC_BUTTON_A11                  1024
#define IDC_BUTTON_I                    1024
#define IDC_EDIT_DOWN_TIME              1024
#define IDC_BUTTON_A12                  1025
#define IDC_BUTTON_J                    1025
#define IDC_LIST_FORMAT                 1025
#define IDC_BUTTON_A13                  1026
#define IDC_BUTTON_K                    1026
#define IDC_BUTTON_A14                  1027
#define IDC_BUTTON_L                    1027
#define IDC_BUTTON_CONFIG_3             1028
#define IDC_BUTTON_A15                  1028
#define IDC_BUTTON_M                    1028
#define IDC_EDIT_CONFIG_3_STATIC        1029
#define IDC_BUTTON_A16                  1029
#define IDC_BUTTON_N                    1029
#define IDC_EDIT_READ_WRITE_CONFIG3     1030
#define IDC_BUTTON_A17                  1030
#define IDC_BUTTON_O                    1030
#define IDC_BUTTON_WRITE_WINDOW3        1031
#define IDC_BUTTON_A18                  1031
#define IDC_BUTTON_P                    1031
#define IDC_BUTTON_CONFIG_4             1032
#define IDC_BUTTON_A19                  1032
#define IDC_BUTTON_S                    1032
#define IDC_EDIT_CONFIG_4_STATIC        1033
#define IDC_BUTTON_A20                  1033
#define IDC_BUTTON_T                    1033
#define IDC_EDIT_READ_WRITE_CONFIG4     1034
#define IDC_BUTTON_A21                  1034
#define IDC_BUTTON_U                    1034
#define IDC_BUTTON_WRITE_WINDOW4        1035
#define IDC_BUTTON_A22                  1035
#define IDC_BUTTON_V                    1035
#define IDC_BUTTON_CONFIG_5             1036
#define IDC_BUTTON_A23                  1036
#define IDC_BUTTON_W                    1036
#define IDC_EDIT_CONFIG_5_STATIC        1037
#define IDC_BUTTON_A24                  1037
#define IDC_BUTTON_X                    1037
#define IDC_EDIT_READ_WRITE_CONFIG5     1038
#define IDC_BUTTON_A25                  1038
#define IDC_BUTTON_Z                    1038
#define IDC_BUTTON_WRITE_WINDOW5        1039
#define IDC_BUTTON_A26                  1039
#define IDC_BUTTON_Y                    1039
#define IDC_BUTTON_CONFIG_6             1040
#define IDC_EDIT_CONFIG_6_STATIC        1041
#define IDC_EDIT_READ_WRITE_CONFIG6     1042
#define IDC_BUTTON_WRITE_WINDOW6        1043
#define IDC_BUTTON_CONFIG_9             1044
#define IDC_EDIT_CONFIG_9_STATIC        1045
#define IDC_EDIT_READ_WRITE_CONFIG9     1046
#define IDC_BUTTON_WRITE_WINDOW9        1047
#define IDC_BUTTON_CONFIG_10            1048
#define IDC_EDIT_CONFIG_10_STATIC       1049
#define IDC_EDIT_READ_WRITE_CONFIG10    1050
#define IDC_BUTTON_WRITE_WINDOW10       1051
#define IDC_BUTTON_CONFIG_11            1052
#define IDC_EDIT_CONFIG_11_STATIC       1053
#define IDC_EDIT_READ_WRITE_CONFIG11    1054
#define IDC_BUTTON_WRITE_WINDOW11       1055
#define IDC_BUTTON_CONFIG_12            1056
#define IDC_EDIT_CONFIG_12_STATIC       1057
#define IDC_EDIT_READ_WRITE_CONFIG12    1058
#define IDC_BUTTON_WRITE_WINDOW12       1059
#define IDC_BUTTON_SET_TIME             1060
#define IDC_DATETIMEPICKER_TIME         1061
#define IDC_DATETIMEPICKER_DATE         1062

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
