#if !defined(_SNWINMSG_H)
#define _SNWINMSG_H

// Windows Messages
#define WM_RX_DATA					WM_USER + 1
#define WM_SEND_COMM_DATA			WM_RX_DATA + 1
#define WM_UPDATE_DATA				WM_SEND_COMM_DATA + 1
#define WM_ERROR_CONDITION			WM_UPDATE_DATA + 1
#define WM_UPDATE_STATUS			WM_ERROR_CONDITION + 1
#define WM_REMOTE_CMD				WM_UPDATE_STATUS + 1
#define	WM_EXIT_DIALOG				WM_REMOTE_CMD + 1
#define WM_UPDATE_REMOTE_STATUS		WM_EXIT_DIALOG + 1
#define WM_CONDOR_CMD				WM_UPDATE_REMOTE_STATUS + 1
#define WM_UPDATE_ACTUAL_VELOCITY	WM_CONDOR_CMD + 1
#endif