//{{NO_DEPENDENCIES}}
// Microsoft eMbedded Visual C++ generated include file.
// Used by Shaver.rc
//
#define SN_MEDIUM_SPEED                 1
#define SN_PUMPING                      2
#define SN_SETTINGS                     3
#define SN_SET_SUCTION                  4
#define SN_LARGE                        5
#define SN_MEDIUM                       6
#define SN_SMALL                        7
#define SN_SET_PRESSURE_MMHG            8
#define SN_SET_FLOW_LIMIT_LMIN          10
#define SN_PRESSURE_MMHG                11
#define SN_FLOW_RATE_LMIN               12
#define SN_PRESS                        13
#define SN_TO_PUMP                      14
#define SN_LAVAGE                       15
#define SN_LAVAGE_START                 16
#define SN_NORMAL                       17
#define SN_TIME                         18
#define SN_DONE                         19
#define SN_SET_SUCTION_LEVELS           20
#define SN_SHAVER_NOT_DETECTED          21
#define SN_PERCENTAGE                   22
#define SN_SHAVER_ON                    23
#define SN_SHAVER_OFF                   24
#define SN_LOW_SPEED                    25
#define SN_HIGH_SPEED                   26
#define SN_OTHER                        27
#define SN_SET                          28
#define SN_CANCEL                       29
#define SN_CUSTOM_PRESSURE_MMHG         30
#define SN_CANNULA                      31
#define SN_STANDARD                     32
#define SN_LARGE_DIAMETER               33
#define SN_SMALL_JOINT                  34
#define SN_SMALL_JOINT_SINGLE_LINE      35
#define SN_LARGE_DIAMETER_SINGLE_LINE   36
#define SN_RESTORE_DEFAULT              37
#define SN_CUSTOM_FLOW_RATE_LIMIT       38
#define SN_CUSTOM_SUCTION               39
#define SN_SHAVER                       40
#define SN_NOT_DETECTED                 41
#define SN_SYSTEM_INFORMATION           42
#define SN_FLUID_MANAGEMENT             43
#define SN_MODEL                        44
#define SN_MODEL_NUMBER                 45
#define SN_VERSION_NUMBER               46
#define SN_VERSION                      47
#define SN_PRESSURE                     48
#define SN_FLOW_RATE_LIMIT              49
#define SN_SUCTION                      50
#define SN_CUSTOM_SETTINGS              51
#define SN_LANGUAGE                     52
#define SN_PURGE                        55
#define SN_PURGING                      56
#define SN_PERIOD                       57
#define SN_PURGING_IN_PROCESS           59
#define SN_PURGE_CASSETTE               60
#define SN_SIZE                         61
#define SN_STOP                         62
#define SN_START                        63
#define SN_PURGE_DONE                   64
#define SN_ENGLISH                      65
#define SN_SELECT_CUSTOM_MODE           66
#define SN_SELECT_DEFAULT_MODE          67
#define SN_IN_CUSTOM_MODE               68
#define SN_IN_DEFAULT_MODE              69
#define SN_PRESS_DONE_WHEN_FINISHED     70
#define SN_OVERPRESSURE                 71
#define SN_OVERPRESSURE_TIMEOUT         72
#define SN_INVALID_CASSETTE_TYPE        74
#define SN_ONE                          80
#define SN_TWO                          81
#define SN_THREE                        82
#define SN_FOUR                         83
#define SN_LAVAGE_STOP                  86
#define SN_CUSTOM_CANNULA               87
#define SN_GRAVITY_INFLOW               88
#define SN_SYSTEM_ERROR                 90
#define SN_SYSTEM_COMM_ERROR            91
#define SN_TRANSDUCER_ERROR             92
#define SN_PUMP_ERROR                   93
#define SN_AIR_IN_TUBING                94
#define SN_TEMPERATURE_FAULT            95
#define SN_TEMPERATURE_ERROR            96
#define SN_SYSTEM_RESOURCE_ERROR        97
#define SN_PINCH_VALVE_ERROR            98
#define SN_NO_INSTRUMENT_DETECTED       99
#define SN_APPLICATION_VERSION          100
#define SN_MOTOR_CONTROLLER_VERSION     101
#define IDD_PUMP_DIALOG                 102
#define IDD_ERROR_DIALOG                102
#define SN_REMOTE_CONTROLL_ERROR        102
#define IDD_SHAVER_DIALOG               102
#define IDD_STATUS_BAR                  102
#define SN_OUTFLOW_CONTROL              103
#define IDD_SERIAL_NUMBER               103
#define SN_LOAD_CASSETTE                104
#define SN_BLADE_SPEED                  105
#define SN_CUSTOM_SETTINGS_SAVE_FAILURE 106
#define SN_CUSTOM_SETTINGS_RETRIEVE_FAILURE 107
#define SN_BATTERY_FAILURE              108
#define SN_ERROR                        109
#define SN_REMOVE_CASSETTE              110
#define SN_NO_CASSETTE                  111
#define SN_INSERT_CASSETTE              112
#define SN_PRESSURE_APPLIED             113
#define SN_TEST_COMPLETE                114
#define SN_FLOW_TEST                    115
#define SN_PRESSURE_P1_MMHG             116
#define SN_PRESSURE_P2_MMHG             117
#define SN_END_TEST                     118
#define SN_FRENCH                       119
#define SN_GERMAN                       120
#define SN_ITALIAN                      121
#define SN_SPANISH                      122
#define SN_WRONG_NO_INSTRUMENT          123
#define SN_LANGUAGE_SELECTION           124
#define SN_LANGUAGE_TEXT                125
#define SN_YES                          126
#define SN_NO                           127
#define SN_STANDARD_SINGLE_LINE         128
#define IDR_MAINFRAME                   128
#define SN_SWEDISH                      129
#define IDD_SELECT_SETTINGS             129
#define SN_DANISH                       130
#define IDB_BITMAP_BK_BUTTON            130
#define SN_DUTCH                        131
#define IDB_BITMAP_BK_BUTTON_PRESSED    131
#define SN_NORWEGIAN                    132
#define IDB_BITMAP_BUTTON_ARROW_UP      132
#define SN_PORTUGUESE                   133
#define IDB_BITMAP_BUTTON_ARROW_UP_PRESSED 133
#define IDB_BITMAP_BUTTON_ARROW_DOWN    134
#define IDB_BITMAP_BUTTON_ARROW_DOWN_PRESSED 135
#define IDB_BITMAP_BUTTON_GRAY          136
#define IDB_BITMAP_BUTTON_GRAY_PRESSED  137
#define IDD_MDU_SETTINGS                138
#define IDB_BITMAP_BUTTON_WINDOW        139
#define IDB_BITMAP_BUTTON_WINDOW_PRESSED 140
#define IDB_BITMAP_GREEN_ARROW_CENTER   141
#define IDB_BITMAP_GREEN_ARROW_LEFT     142
#define IDB_BITMAP_GREEN_ARROW_RIGHT    143
#define IDB_BITMAP_GREEN_ARROW_LARGE_LEFT 144
#define IDD_MDU_PROCEDURE               145
#define IDD_MDU_TOOL_SETTINGS           146
#define IDD_MDU_TOOL_PROCEDURE          147
#define IDB_BITMAP_GREEN_ARROW_LARGE_RIGHT 148
#define IDD_TOOL_PROCEDURE              149
#define IDD_SETTINGS                    150
#define IDB_BITMAP_GRAY_BUTTON_ROUND    151
#define IDB_BITMAP_GRAY_BUTTON_ROUND_PRESSED 152
#define IDD_SYSTEM_INFO                 153
#define IDD_LANGUAGE                    154
#define IDD_OSCILLATION_PROFILE         155
#define IDB_BITMAP_GRAY_BUTTON_RADIO_SMALL 156
#define IDB_BITMAP_BLACK_DOT            157
#define IDB_BITMAP_GRAY_BUTTON_RADIO    158
#define IDB_BITMAP_MODE1                159
#define IDB_BITMAP_MODE2                160
#define IDB_BITMAP_MODE3                161
#define IDB_BITMAP_MODE4                162
#define IDB_BITMAP_ARROW_LEFT           163
#define IDB_BITMAP_ARROW_RIGHT          164
#define IDB_BITMAP_BLANK                165
#define IDB_BITMAP_MODE1_ICON           167
#define IDB_BITMAP_MODE2_ICON           168
#define IDB_BITMAP_MODE3_ICON           169
#define IDB_BITMAP_MODE4_ICON           170
#define IDB_BITMAP_SHAVER_ICON          171
#define IDB_BITMAP_SHAVER_ICON_PORTA    171
#define IDB_BITMAP_PUMP_BLUE_ICON       172
#define IDB_BITMAP_PUMP_ROTATE_120      173
#define IDB_BITMAP_PUMP_ROTATE_150      174
#define IDB_BITMAP_PUMP_ROTATE_30       175
#define IDB_BITMAP_PUMP_ROTATE_60       176
#define IDB_BITMAP_SAW_ICON             177
#define IDB_BITMAP_SAW_ICON_PORTA       177
#define IDB_BITMAP_DRILL_ICON           178
#define IDB_BITMAP_DRILL_ICON_PORTA     178
#define IDB_BITMAP_FOOT_PEDAL_ICON      179
#define IDB_BITMAP_FOOT_PEDAL_ICON_PORTA 179
#define IDB_BITMAP_ARROW_LEFT_SMALL     180
#define IDB_BITMAP_ARROW_RIGHT_SMALL    181
#define IDB_BITMAP_BLANK_SMALL          182
#define IDD_TOOL_SETTINGS               183
#define IDB_BITMAP_GRAY_BUTTON_ON       184
#define IDB_BITMAP_GRAY_BUTTON_OFF      185
#define IDB_BITMAP_GRAY_BUTTON_SMALL_OFF 186
#define IDB_BITMAP_GRAY_BUTTON_SMALL_ON 187
#define IDD_ICON_STATUS_BAR             189
#define IDD_LANGUAGE_POPUP              190
#define IDB_BITMAP_GRAY_BUTTON_ROUND_WHITEBK 191
#define IDB_BITMAP_GRAY_BUTTON_ROUND_PRESSED_WHITEBK 192
#define IDD_DIALOG1                     193
#define IDD_PROCEDURE                   195
#define IDD_SYSTEM_ERROR                196
#define IDD_FOOTSWITCH                  197
#define IDD_OSC_MODE                    198
#define IDB_BITMAP_CONNECTED_BRIDGE_ICON 199
#define IDB_BITMAP_ARROW_LEFT_WHITE     200
#define SN_SHAVER_MODEL_NUMBER          201
#define IDB_BITMAP_ARROW_RIGHT_WHITE    201
#define SN_WINDOW                       202
#define IDB_BITMAP_BUTTON_FORWARD       202
#define SN_RPM                          203
#define IDB_BITMAP_BUTTON_REVERSE       203
#define SN_SPEED                        204
#define IDB_BITMAP_BUTTON_OSCILLATE     204
#define IDB_BITMAP_DIRECTION_PRESSED    205
#define SN_DYONICS_POWER_SHAVER         206
#define IDD_MESSAGE_BOX                 206
#define SN_OSCILLATE_MODE               207
#define IDB_BITMAP_PUMP_GRAY_ICON       207
#define SN_DEFAULT_PAREN                208
#define IDD_REMOTE_SETTINGS             208
#define SN_FOOTSWITCH                   209
#define IDB_BITMAP_GRAY_BUTTON_DISABLED 209
#define SN_DEFAULT                      210
#define IDB_BITMAP_DRILL_ICON_PORTB     210
#define SN_OSCILLATE_MODE1              211
#define IDB_BITMAP_FOOT_PEDAL_ICON_PORTB 211
#define SN_OSCILLATE_MODE2              212
#define IDB_BITMAP_SHAVER_ICON_PORTB    212
#define SN_SECONDS                      213
#define IDB_BITMAP_SAW_ICON_PORTB       213
#define SN_REVOLUTIONS                  214
#define IDB_BITMAP_GRAY_BUTTON_LARGE    214
#define SN_MODE                         215
#define IDB_BITMAP_GRAY_BUTTON_LARGE_PRESSED 215
#define SN_FORWARD                      216
#define IDD_FACTORY                     216
#define SN_HAND_CONTROL_OVERRIDE        217
#define IDD_TEST_MODE                   217
#define SN_ON_OFF                       218
#define SN_VARIABLE                     219
#define IDB_COPYRIGHT                   219
#define SN_LEFT                         220
#define IDB_BITMAP_GRAY_BUTTON_LARGE_ON 220
#define SN_RIGHT                        221
#define IDB_BITMAP_GRAY_BUTTON_LARGE_OFF 221
#define SN_ON                           222
#define SN_OFF                          223
#define IDB_BITMAP_BAR_GRAPH1           223
#define SN_BUR                          224
#define IDB_BITMAP_BAR_GRAPH2           224
#define SN_STRAIGHT                     225
#define IDB_BITMAP_BAR_GRAPH3           225
#define SN_FAST_BUR                     226
#define IDB_BITMAP_BAR_GRAPH4           226
#define SN_CURVED                       227
#define IDB_BITMAP_BAR_GRAPH5           227
#define SN_BLADE_INVALID                228
#define IDB_BITMAP_BAR_GRAPH6           228
#define SN_PORT_CONTROL                 229
#define IDB_BITMAP_BAR_GRAPH7           229
#define SN_PORTA                        230
#define IDB_BITMAP_BAR_GRAPH8           230
#define SN_PORTB                        231
#define IDB_BITMAP_CONNECTOR_PORTA      231
#define SN_INTERFACE                    232
#define IDB_BITMAP_CONNECTOR_PORTB      232
#define SN_INVALID_BLADE_ID             233
#define IDB_BITMAP_BUTTON_DELTA_MODE    233
#define SN_INVALID_DEVICE_ID            234
#define IDB_BITMAP_BUTTON_DELTA_MODE_PRESSED 234
#define SN_INVALID_HALL_PATTERN         235
#define IDB_BITMAP_GRAY_ROUND_BLUE_RING 235
#define SN_MOTOR_STALL                  236
#define IDB_BITMAP_GRAY_ROUND_YELLOW_RING 236
#define SN_MOTOR_TAC_FAULT              237
#define IDB_BITMAP_COMBO_ICON_PORTA     237
#define SN_SHORT_CIRCUIT_DETECTED       238
#define IDB_BITMAP_COMBO_ICON_PORTB     238
#define SN_FOOT_STUCK_PEDAL             239
#define IDB_BITMAP_BTN_CHECK_MARK       239
#define SN_FOOT_LOW_BATTERY             240
#define IDB_BITMAP_BTN_X_MARK           240
#define SN_TEMPERATURE_FAULT_DETAIL     241
#define IDD_PROCEDURE_CHILD             241
#define SN_OK                           242
#define SN_WARNING                      243
#define SN_MOTOR_STALL_DETAIL           244
#define SN_MOTOR_TAC_FAULT_DETAIL       245
#define SN_MOTOR_CURRENT_LIMIT          246
#define SN_MOTOR_TORQUE_LIMIT           247
#define SN_SET_SPEEDS_SAVE_FAILURE      248
#define SN_SET_SPEEDS_RETRIEVE_FAILURE  249
#define SN_INVALID_DEVICE_ID_DETAIL     250
#define SN_INVALID_BLADE_ID_DETAIL      251
#define SN_SHORT_CIRCUIT_DETAIL         252
#define SN_UNKNOWN_FOOT_ID              253
#define SN_UNKNOWN_FOOT_ID_DETAIL       254
#define SN_HAND_STUCK_BUTTON            255
#define SN_HAND_STUCK_BUTTON_DETAIL     256
#define SN_FOOT_STUCK_PEDAL_DETAIL      257
#define SN_MOTOR_CURRENT_LIMIT_TIMEOUT  258
#define SN_MOTOR_CURRENT_LIMIT_DETAIL   259
#define SN_MOTOR_CURRENT_LIMIT_TIMEOUT_DETAIL 260
#define SN_MOTOR_STALL_AND_CURRENT_LIMIT 261
#define SN_MOTOR_STALL_AND_CURRENT_LIMIT_DETAIL 262
#define SN_INVALID_HALL_PATTERN_DETAIL  263
#define SN_FOOT_LOW_BATTERY_DETAIL      264
#define SN_FOOTSWITCH_REQUIRED          265
#define SN_FOOTSWITCH_REQUIRED_DETAIL   266
#define SN_IN_BLADE_DEFAULT             267
#define SN_IN_BLADE_RECALL              268
#define SN_SELECT_BLADE_DEFAULT         269
#define SN_SELECT_BLADE_RECALL          270
#define SN_FOOTSWITCH_VERSION           271
#define SN_ADJUST                       273
#define SN_FACTORY_DEFAULT              274
#define SN_ARE_YOU_SURE                 275
#define SN_SET_OSCILLATE_PERIOD         276
#define SN_SET_NUMBER_REVOLUTIONS       277
#define SN_MODE1                        278
#define SN_MODE2                        279
#define SN_RATE                         280
#define SN_A                            281
#define SN_B                            282
#define SN_BLADE_RESET                  283
#define SN_SYSTEM_RESET                 284
#define SN_HANDPIECE_VERSION_PORTA      285
#define SN_HANDPIECE_VERSION_PORTB      286
#define IDC_BUTTON_SETTINGS             1000
#define IDC_BUTTON_WINDOW               1001
#define IDC_BUTTON_RESTORE_DEFAULT1     1002
#define IDC_BUTTON_RESTORE_DEFAULT2     1003
#define IDC_BUTTON_RESTORE_DEFAULT3     1004
#define IDC_BUTTON_ARROW_DOWN1          1005
#define IDC_BUTTON_ARROW_UP1            1006
#define IDC_STATIC_TEXT1                1007
#define IDC_STATIC_RPM1                 1008
#define IDC_BUTTON_ARROW_DOWN2          1009
#define IDC_BUTTON_ARROW_UP2            1010
#define IDC_STATIC_RPM                  1010
#define IDC_BUTTON_ARROW_DOWN3          1011
#define IDC_STATIC_SPEED                1011
#define IDC_BUTTON_DONE                 1011
#define IDC_BUTTON_ARROW_UP3            1012
#define IDC_STATIC_TITLE                1012
#define IDC_STATIC_TEXT2                1013
#define IDC_BUTTON_CUSTOM_SETTINGS      1013
#define IDC_STATIC_MESSAGE_TEXT         1013
#define IDC_STATIC_TEXT3                1014
#define IDC_BUTTON_SYSTEM_INFORMATION   1014
#define IDC_STATIC1                     1014
#define IDC_BUTTON_INTERFACE_CTL        1014
#define IDC_STATIC_MESSAGE_TEXT2        1014
#define IDC_STATIC_RPM2                 1015
#define IDC_BUTTON_LANGUAGE             1015
#define IDC_STATIC2                     1015
#define IDC_BUTTON_RESTORE_DEFAULT4     1016
#define IDC_STATIC_SYSTEM_INFORMATION   1016
#define IDC_STATIC3                     1016
#define IDC_STATIC_INTERFACE_CTL        1016
#define IDC_BUTTON_ARROW_DOWN4          1017
#define IDC_STATIC_LANGUAGE             1017
#define IDC_STATIC_MODEL                1017
#define IDC_BUTTON_ARROW_UP4            1018
#define IDC_STATIC_CUSTOM_SETTINGS      1018
#define IDC_STATIC_VERSION              1018
#define IDC_STATIC_TEXT4                1019
#define IDC_BUTTON_LANGUAGE1            1019
#define IDC_STATIC4                     1019
#define IDC_BUTTON_FOOTSWITCH           1019
#define IDC_BUTTON_LANGUAGE2            1020
#define IDC_BUTTON_MODE1                1020
#define IDC_STATIC_VERSION_APP          1020
#define IDC_STATIC_FOOTSWITCH           1020
#define IDC_BUTTON_LANGUAGE3            1021
#define IDC_BUTTON_MODE2                1021
#define IDC_STATIC5                     1021
#define IDC_BUTTON_INTERFACE            1021
#define IDC_BUTTON_LANGUAGE4            1022
#define IDC_BUTTON_MODE3                1022
#define IDC_STATIC_VERSION_MC           1022
#define IDC_STATIC_INTERFACE            1022
#define IDC_BUTTON_LANGUAGE5            1023
#define IDC_BUTTON_MODE4                1023
#define IDC_STATIC6                     1023
#define IDC_BUTTON_LANGUAGE6            1024
#define IDC_STATIC_DEFAULT              1024
#define IDC_STATIC_VERSION_FOOT         1024
#define IDC_BUTTON_LANGUAGE7            1025
#define IDC_STATIC_SPEED_PERCENT        1025
#define IDC_STATIC_COPYRIGHT            1025
#define IDC_BUTTON_LANGUAGE8            1026
#define IDC_STATIC_BITMAP1              1026
#define IDC_STATIC_PORTA_BITMAP1        1026
#define IDC_STATIC7                     1026
#define IDC_BUTTON_LANGUAGE9            1027
#define IDC_STATIC_BITMAP2              1027
#define IDC_STATIC_PORTA_BITMAP2        1027
#define IDC_STATIC8                     1027
#define IDC_BUTTON_LANGUAGE10           1028
#define IDC_STATIC_BITMAP3              1028
#define IDC_STATIC_PORTA_BITMAP3        1028
#define IDC_STATIC_VERSION_PORTA        1028
#define IDC_STATIC_VERSION_PORTB        1029
#define IDC_STATIC_BITMAP4              1029
#define IDC_STATIC_PORTB_BITMAP1        1029
#define IDC_STATIC_BITMAP5              1030
#define IDC_STATIC_BITMAP_PUMP          1030
#define IDC_STATIC9                     1030
#define IDC_STATIC_BITMAP6              1031
#define IDC_STATIC_BITMAP_CONNECTED_BRIDGE 1031
#define IDC_STATIC_MODEL2               1031
#define IDC_STATIC_BITMAP7              1032
#define IDC_STATIC_PORTB_BITMAP2        1032
#define IDC_STATIC_BITMAP8              1033
#define IDC_STATIC_PORTB_BITMAP3        1033
#define IDC_STATIC_BITMAP9              1034
#define IDC_STATIC_BITMAP_SPEED1        1034
#define IDC_STATIC_BITMAP_PUMP2         1034
#define IDC_STATIC_BITMAP10             1035
#define IDC_STATIC_BITMAP_SPEED2        1035
#define IDC_BUTTON1                     1035
#define IDC_BUTTON_YES                  1035
#define IDC_BUTTON_DEFAULT              1035
#define IDC_BUTTON_OK                   1035
#define IDC_BUTTON_LEFT                 1035
#define IDC_BTN_ENGLISH                 1035
#define IDC_BUTTON_ADJUST_PORTA         1035
#define IDC_BUTTON_RESET                1035
#define IDC_STATIC_BITMAP11             1036
#define IDC_BUTTON_DEMO                 1036
#define IDC_BUTTON_NO                   1036
#define IDC_BUTTON_MODE                 1036
#define IDC_BUTTON_MIDDLE               1036
#define IDC_BUTTON_ADJUST_PORTB         1036
#define IDC_BUTTON_ACCEPT               1036
#define IDC_BUTTON_NUMPAD_7             1036
#define IDC_STATIC_BITMAP12             1037
#define IDC_RADIO1                      1037
#define IDC_BUTTON_SET_DEFAULT          1037
#define IDC_BUTTON_RESET_BLADE_A        1037
#define IDC_BUTTON_NUMPAD_8             1037
#define IDC_STATIC_BITMAP13             1038
#define IDC_STATIC_BITMAP_SPEED3        1038
#define IDC_STATIC_ARROW_DOWN1          1038
#define IDC_BUTTON_RESET_BLADE_B        1038
#define IDC_BUTTON_NUMPAD_9             1038
#define IDC_STATIC_BITMAP14             1039
#define IDC_STATIC_BITMAP_SPEED4        1039
#define IDC_STATIC_ARROW_UP1            1039
#define IDC_BUTTON_RIGHT                1039
#define IDC_BUTTON_NUMPAD_4             1039
#define IDC_STATIC_BITMAP15             1040
#define IDC_STATIC_BITMAP_SPEED5        1040
#define IDC_STATIC_ARROW_DOWN2          1040
#define IDC_BUTTON_NUMPAD_5             1040
#define IDC_STATIC_BITMAP16             1041
#define IDC_STATIC_BITMAP_SPEED6        1041
#define IDC_STATIC_ARROW_DOWN3          1041
#define IDC_BUTTON_NUMPAD_6             1041
#define IDC_STATIC_BITMAP17             1042
#define IDC_STATIC_BITMAP_SPEED7        1042
#define IDC_STATIC_ARROW_DOWN4          1042
#define IDC_BUTTON_NUMPAD_1             1042
#define IDC_STATIC_BITMAP18             1043
#define IDC_STATIC_BITMAP_SPEED8        1043
#define IDC_STATIC_ARROW_UP2            1043
#define IDC_BUTTON_NUMPAD_2             1043
#define IDC_STATIC_BITMAP19             1044
#define IDC_STATIC_BITMAP_SPEED9        1044
#define IDC_STATIC_ARROW_UP3            1044
#define IDC_STATIC_BITMAP_SPEED10       1045
#define IDC_STATIC_ARROW_UP4            1045
#define IDC_BUTTON_NUMPAD_3             1045
#define IDC_STATIC_BITMAP_SPEED11       1046
#define IDC_BUTTON_NUMPAD_UP            1046
#define IDC_STATIC_BITMAP_SPEED12       1047
#define IDC_BUTTON_NUMPAD_0             1047
#define IDC_STATIC_BITMAP_SPEED13       1048
#define IDC_BUTTON_NUMPAD_DOWN          1048
#define IDC_STATIC_BITMAP_SPEED14       1049
#define IDC_BUTTON_NUMPAD_DEL           1049
#define IDC_S_ARROW_DOWN1               1050
#define IDC_BUTTON_NUMPAD_ENTER         1050
#define IDC_S_ARROW_UP1                 1051
#define IDC_STATIC_ARROW_D1             1051
#define IDC_S_ARROW_DOWN2               1052
#define IDC_STATIC_ARROW_U1             1052
#define IDC_BUTTON2                     1053
#define IDC_S_ARROW_UP2                 1054
#define IDC_STATIC_BUTTON_MODE1         1054
#define IDC_STATIC_BUTTON_MODE2         1055
#define IDC_STATIC_BUTTON_LANGUAGE1     1055
#define IDC_STATIC_BUTTON_MODE3         1056
#define IDC_STATIC_BUTTON_LANGUAGE2     1056
#define IDC_STATIC_BUTTON_MODE4         1057
#define IDC_STATIC_BUTTON_LANGUAGE3     1057
#define IDC_STATIC_BUTTON_LANGUAGE4     1058
#define IDC_STATIC_BUTTON_DEFAULT1      1058
#define IDC_STATIC_BUTTON_LANGUAGE5     1059
#define IDC_STATIC_BUTTON_DEFAULT2      1059
#define IDC_STATIC_BUTTON_LANGUAGE6     1060
#define IDC_STATIC_BUTTON_LANGUAGE7     1061
#define IDC_STATIC_BUTTON_LANGUAGE8     1062
#define IDC_STATIC_BUTTON_LANGUAGE9     1063
#define IDC_STATIC_BUTTON_LANGUAGE10    1064
#define IDC_STATIC_LANGUAGE3            1065
#define IDC_STATIC_TEXT                 1066
#define IDC_BITMAP_PORTA_DIRECTION1     1067
#define IDC_STATIC_LANGUAGE2            1068
#define IDC_BITMAP_PORTA_DIRECTION2     1068
#define IDC_BITMAP_PORTA_DIRECTION3     1069
#define IDC_STATIC_LANGUAGE4            1070
#define IDC_BITMAP_PORTA_DIRECTION4     1070
#define IDC_STATIC_LANGUAGE5            1071
#define IDC_BITMAP_PORTA_DIRECTION5     1071
#define IDC_STATIC_LANGUAGE6            1072
#define IDC_BITMAP_PORTA_DIRECTION6     1072
#define IDC_STATIC_LANGUAGE7            1073
#define IDC_BITMAP_PORTA_DIRECTION7     1073
#define IDC_STATIC_LANGUAGE8            1074
#define IDC_BITMAP_PORTA_DIRECTION8     1074
#define IDC_STATIC_LANGUAGE10           1075
#define IDC_BITMAP_PORTA_DIRECTION9     1075
#define IDC_STATIC_LANGUAGE9            1076
#define IDC_BITMAP_PORTA_DIRECTION10    1076
#define IDC_STATIC_LANGUAGE1            1077
#define IDC_BITMAP_PORTA_DIRECTION11    1077
#define IDC_BITMAP_PORTA_DIRECTION12    1078
#define IDC_BITMAP_PORTA_DIRECTION13    1079
#define IDC_BITMAP_PORTA_DIRECTION14    1080
#define IDC_BITMAP_PORTB_DIRECTION1     1081
#define IDC_BITMAP_PORTB_DIRECTION2     1082
#define IDC_BITMAP_PORTB_DIRECTION3     1083
#define IDC_BITMAP_PORTB_DIRECTION4     1084
#define IDC_BITMAP_PORTB_DIRECTION5     1085
#define IDC_BITMAP_PORTB_DIRECTION6     1086
#define IDC_BITMAP_PORTB_DIRECTION7     1087
#define IDC_BITMAP_PORTB_DIRECTION8     1088
#define IDC_BITMAP_PORTB_DIRECTION9     1089
#define IDC_BITMAP_PORTB_DIRECTION10    1090
#define IDC_BITMAP_PORTB_DIRECTION11    1091
#define IDC_BITMAP_PORTB_DIRECTION12    1092
#define IDC_BITMAP_PORTB_DIRECTION13    1093
#define IDC_BITMAP_PORTB_DIRECTION14    1094
#define IDC_CUSTOM2                     1096
#define IDC_BUTTON_SET                  1097
#define IDC_BUTTON_CANCEL               1098
#define IDC_STATIC_BUTTON_UP            1099
#define IDC_STATIC_BUTTON_DOWN          1100
#define IDC_STATIC_BUTTON_LEFT          1100
#define IDC_STATIC_BUTTON_RIGHT         1101
#define IDC_STATIC_BUTTON_ON            1102
#define IDC_HELP_CENTER                 1102
#define IDC_STATIC_BUTTON_OFF           1103
#define IDC_STATIC_ACTUAL_VEL_PORTA     1103
#define IDC_STATIC_ACTUAL_VEL_PORTB     1104
#define IDC_STATIC_BUTTON_PORTA         1104
#define IDC_STATIC_TEMP                 1104
#define IDC_STATIC_BUTTON_PORTB         1105
#define IDC_STATIC_MODE                 1105
#define IDC_STATIC_TEST_LIST_TITLE      1106
#define IDC_STATIC_INSTRUCTIONS_TITLE   1107
#define IDC_STATIC_TEST_TITLE           1108
#define IDC_EDIT_TEST_LIST_TEXT         1109
#define IDC_STATIC_USAGE_CNT            1110
#define IDC_STATIC_INSTRUCTIONS_TEXT    1111
#define IDC_STATIC_TEST_TEXT            1112
#define IDC_STATIC_BUTTON_YEAR          1114
#define IDC_STATIC_BUTTON_MONTH         1115
#define IDC_STATIC_BUTTON_DAY           1116
#define IDC_STATIC_BUTTON_HOUR          1117
#define IDC_STATIC_BUTTON_MINUTE        1118
#define IDC_STATIC_BUTTON_SECOND        1119
#define IDC_STATIC_BUTTON_RTC_UP        1120
#define IDC_COMBO1                      1120
#define IDC_STATIC_BUTTON_RTC_DOWN      1121
#define IDC_LIST1                       1121
#define IDC_LIST2                       1122
#define IDC_FATAL_ERROR_TEXT            1123
#define IDC_BITMAP_BARGRAPH             1124
#define IDC_STATIC_RESET                1125

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        242
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1126
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
