//{{NO_DEPENDENCIES}}
// Microsoft eMbedded Visual C++ generated include file.
// Used by SwedishRes.rc
//
#define SN_MEDIUM_SPEED                 1
#define SN_PUMPING                      2
#define SN_SETTINGS                     3
#define SN_SET_SUCTION                  4
#define SN_LARGE                        5
#define SN_MEDIUM                       6
#define SN_SMALL                        7
#define SN_SET_PRESSURE_MMHG            8
#define SN_SET_FLOW_LIMIT_LMIN          10
#define SN_PRESSURE_MMHG                11
#define SN_FLOW_RATE_LMIN               12
#define SN_PRESS                        13
#define SN_TO_PUMP                      14
#define SN_LAVAGE                       15
#define SN_LAVAGE_START                 16
#define SN_NORMAL                       17
#define SN_TIME                         18
#define SN_DONE                         19
#define SN_SET_SUCTION_LEVELS           20
#define SN_SHAVER_NOT_DETECTED          21
#define SN_PERCENTAGE                   22
#define SN_SHAVER_ON                    23
#define SN_SHAVER_OFF                   24
#define SN_LOW_SPEED                    25
#define SN_HIGH_SPEED                   26
#define SN_OTHER                        27
#define SN_SET                          28
#define SN_CANCEL                       29
#define SN_CUSTOM_PRESSURE_MMHG         30
#define SN_CANNULA                      31
#define SN_STANDARD                     32
#define SN_LARGE_DIAMETER               33
#define SN_SMALL_JOINT                  34
#define SN_SMALL_JOINT_SINGLE_LINE      35
#define SN_LARGE_DIAMETER_SINGLE_LINE   36
#define SN_RESTORE_DEFAULT              37
#define SN_CUSTOM_FLOW_RATE_LIMIT       38
#define SN_CUSTOM_SUCTION               39
#define SN_SHAVER                       40
#define SN_NOT_DETECTED                 41
#define SN_SYSTEM_INFORMATION           42
#define SN_FLUID_MANAGEMENT             43
#define SN_MODEL                        44
#define SN_MODEL_NUMBER                 45
#define SN_VERSION_NUMBER               46
#define SN_VERSION                      47
#define SN_PRESSURE                     48
#define SN_FLOW_RATE_LIMIT              49
#define SN_SUCTION                      50
#define SN_CUSTOM_SETTINGS              51
#define SN_LANGUAGE                     52
#define SN_PURGE                        55
#define SN_PURGING                      56
#define SN_PERIOD                       57
#define SN_PURGING_IN_PROCESS           59
#define SN_PURGE_CASSETTE               60
#define SN_SIZE                         61
#define SN_STOP                         62
#define SN_START                        63
#define SN_PURGE_DONE                   64
#define SN_ENGLISH                      65
#define SN_SELECT_CUSTOM_MODE           66
#define SN_SELECT_DEFAULT_MODE          67
#define SN_IN_CUSTOM_MODE               68
#define SN_IN_DEFAULT_MODE              69
#define SN_PRESS_DONE_WHEN_FINISHED     70
#define SN_OVERPRESSURE                 71
#define SN_OVERPRESSURE_TIMEOUT         72
#define SN_INVALID_CASSETTE_TYPE        74
#define SN_LAVAGE_STOP                  86
#define SN_CUSTOM_CANNULA               87
#define SN_GRAVITY_INFLOW               88
#define SN_SYSTEM_ERROR                 90
#define SN_SYSTEM_COMM_ERROR            91
#define SN_TRANSDUCER_ERROR             92
#define SN_PUMP_ERROR                   93
#define SN_AIR_IN_TUBING                94
#define SN_TEMPERATURE_FAULT            95
#define SN_TEMPERATURE_ERROR            96
#define SN_SYSTEM_RESOURCE_ERROR        97
#define SN_PINCH_VALVE_ERROR            98
#define SN_NO_INSTRUMENT_DETECTED       99
#define SN_APPLICATION_VERSION          100
#define SN_MOTOR_CONTROLLER_VERSION     101
#define IDD_PUMP_DIALOG                 102
#define IDD_ERROR_DIALOG                102
#define SN_REMOTE_CONTROLL_ERROR        102
#define SN_OUTFLOW_CONTROL              103
#define SN_LOAD_CASSETTE                104
#define SN_BLADE_SPEED                  105
#define SN_CUSTOM_SETTINGS_SAVE_FAILURE 106
#define SN_CUSTOM_SETTINGS_RETRIEVE_FAILURE 107
#define SN_BATTERY_FAILURE              108
#define SN_ERROR                        109
#define SN_REMOVE_CASSETTE              110
#define SN_NO_CASSETTE                  111
#define SN_INSERT_CASSETTE              112
#define SN_PRESSURE_APPLIED             113
#define SN_TEST_COMPLETE                114
#define SN_FLOW_TEST                    115
#define SN_PRESSURE_P1_MMHG             116
#define SN_PRESSURE_P2_MMHG             117
#define SN_END_TEST                     118
#define SN_FRENCH                       119
#define SN_GERMAN                       120
#define SN_ITALIAN                      121
#define SN_SPANISH                      122
#define SN_WRONG_NO_INSTRUMENT          123
#define SN_LANGUAGE_SELECTION           124
#define SN_LANGUAGE_TEXT                125
#define SN_YES                          126
#define SN_NO                           127
#define SN_STANDARD_SINGLE_LINE         128
#define SN_SWEDISH                      129
#define SN_DANISH                       130
#define SN_DUTCH                        131
#define SN_NORWEGIAN                    132
#define SN_PORTUGUESE                   133
#define SN_INCOMPLETE_CASSETTE_INSERTION 134
#define SN_RESTART_CONTROL              135
#define SN_HIGH_FLOW                    136
#define SN_MEDIUM_FLOW                  137
#define SN_LOW_FLOW                     138
#define SN_LOW_FLOW_CANNULA             139
#define SN_MEDIUM_FLOW_CANNULA          140
#define SN_HIGH_FLOW_CANNULA            141
#define SN_REMOTE_CONTROL_BATTERY_LOW   142
#define SN_SHAVER_MODEL_NUMBER          201
#define SN_WINDOW                       202
#define SN_RPM                          203
#define SN_SPEED                        204
#define SN_DYONICS_POWER_SHAVER         206
#define SN_OSCILLATE_MODE               207
#define SN_DEFAULT_PAREN                208
#define SN_FOOTSWITCH                   209
#define SN_DEFAULT                      210
#define SN_OSCILLATE_MODE1              211
#define SN_OSCILLATE_MODE2              212
#define SN_SECONDS                      213
#define SN_REVOLUTIONS                  214
#define SN_MODE                         215
#define SN_FORWARD                      216
#define SN_HAND_CONTROL_OVERRIDE        217
#define SN_ON_OFF                       218
#define SN_VARIABLE                     219
#define SN_LEFT                         220
#define SN_RIGHT                        221
#define SN_ON                           222
#define SN_OFF                          223
#define SN_BUR                          224
#define SN_STRAIGHT                     225
#define SN_FAST_BUR                     226
#define SN_CURVED                       227
#define SN_BLADE_INVALID                228
#define SN_PORT_CONTROL                 229
#define SN_PORTA                        230
#define SN_PORTB                        231
#define SN_INTERFACE                    232
#define SN_INVALID_BLADE_ID             233
#define SN_INVALID_DEVICE_ID            234
#define SN_INVALID_HALL_PATTERN         235
#define SN_MOTOR_STALL                  236
#define SN_MOTOR_TAC_FAULT              237
#define SN_SHORT_CIRCUIT_DETECTED       238
#define SN_FOOT_STUCK_PEDAL             239
#define SN_FOOT_LOW_BATTERY             240
#define SN_TEMPERATURE_FAULT_DETAIL     241
#define SN_OK                           242
#define SN_WARNING                      243
#define SN_MOTOR_STALL_DETAIL           244
#define SN_MOTOR_TAC_FAULT_DETAIL       245
#define SN_MOTOR_CURRENT_LIMIT          246
#define SN_MOTOR_TORQUE_LIMIT           247
#define SN_SET_SPEEDS_SAVE_FAILURE      248
#define SN_SET_SPEEDS_RETRIEVE_FAILURE  249
#define SN_INVALID_DEVICE_ID_DETAIL     250
#define SN_INVALID_BLADE_ID_DETAIL      251
#define SN_SHORT_CIRCUIT_DETAIL         252
#define SN_UNKNOWN_FOOT_ID              253
#define SN_UNKNOWN_FOOT_ID_DETAIL       254
#define SN_HAND_STUCK_BUTTON            255
#define SN_HAND_STUCK_BUTTON_DETAIL     256
#define SN_FOOT_STUCK_PEDAL_DETAIL      257
#define SN_MOTOR_CURRENT_LIMIT_TIMEOUT  258
#define SN_MOTOR_CURRENT_LIMIT_DETAIL   259
#define SN_MOTOR_CURRENT_LIMIT_TIMEOUT_DETAIL 260
#define SN_MOTOR_STALL_AND_CURRENT_LIMIT 261
#define SN_MOTOR_STALL_AND_CURRENT_LIMIT_DETAIL 262
#define SN_INVALID_HALL_PATTERN_DETAIL  263
#define SN_FOOT_LOW_BATTERY_DETAIL      264
#define SN_FOOTSWITCH_REQUIRED          265
#define SN_FOOTSWITCH_REQUIRED_DETAIL   266
#define SN_IN_BLADE_DEFAULT             267
#define SN_IN_BLADE_RECALL              268
#define SN_SELECT_BLADE_DEFAULT         269
#define SN_SELECT_BLADE_RECALL          270
#define SN_FOOTSWITCH_VERSION           271
#define SN_ADJUST                       273
#define SN_FACTORY_DEFAULT              274
#define SN_ARE_YOU_SURE                 275
#define SN_SET_OSCILLATE_PERIOD         276
#define SN_SET_NUMBER_REVOLUTIONS       277
#define SN_MODE1                        278
#define SN_MODE2                        279
#define SN_RATE                         280
#define SN_A                            281
#define SN_B                            282
#define SN_BLADE_RESET                  283
#define SN_SYSTEM_RESET                 284
#define SN_HANDPIECE_VERSION_PORTA      285
#define SN_HANDPIECE_VERSION_PORTB      286
#define SN_START_LOWER_CASE             300
#define SN_READING_FLASH_DATA           301
#define SN_WRITING_FLASH_DATA           302
#define SN_VERIFYING_FLASH_DATA         303
#define SN_READING_FLASH_DATA_FAILED    304
#define SN_WRITING_FLASH_DATA_FAILED    305
#define SN_VERIFYING_FLASH_DATA_FAILED  306
#define SN_REPAIR_COMPLETE              307
#define SN_ALL_FLASH_DATA_CORRUPT_REPAIR_NOT_POSSIBLE 308
#define SN_LOWER_FLASH_DATA_CORRUPT     309
#define SN_UPPER_FLASH_DATA_CORRUPT     310
#define SN_SOFTWARE_UPGRADE_ERROR       311
#define SN_SOFTWARE_UPGRADE             312
#define SN_DRIVER_INTERFACE_FAILED      313
#define SN_ERROR_READING_HEADER_TYPE    314
#define SN_HEADER_INVALID_CRC           315
#define SN_FAILED_SEEK_END_CE_UPDATE    316
#define SN_ERROR_ALLOCATING_MEMORY      317
#define SN_ERROR_READING_IMAGE_DATA     318
#define SN_SPLASH_DATA_INVALID_CRC      319
#define SN_CE_INVALID_CRC               320
#define SN_FAILED_SEEK_END_MOTOR_UPDATE 323
#define SN_ERROR_READING_PROGRAM_FLASH_PAGE 324
#define SN_ERROR_WRITING_PROGRAM_FLASH_PAGE 325
#define SN_CRC_ERROR_READING_PROGRAM_FLASH 326
#define SN_ERROR_READING_DATA_FLASH_PAGE 328
#define SN_ERROR_WRITING_DATA_FLASH_PAGE 329
#define SN_CRC_ERROR_READING_DATA_FLASH 330
#define SN_UNKNOWN_IMAGE_HEADER_TYPE    331
#define SN_FLASH_VERIFY_FAILED          332
#define SN_UPGRADE_SOFTWARE_OK_TO_CONTINUE 333
#define SN_UPGRADE_COMPLETE             334
#define SN_WRITING_LOWER_FLASH_DATA     335
#define SN_WRITING_UPPER_FLASH_DATA     336
#define SN_VERIFYING_LOWER_FLASH_DATA   337
#define SN_VERIFYING_UPPER_FLASH_DATA   338
#define SN_VERIFYING_LOWER_FLASH_DATA_FAILED 339
#define SN_VERIFYING_UPPER_FLASH_DATA_FAILED 340
#define SN_WRITING_LOWER_FLASH_DATA_FAILED 341
#define SN_WRITING_UPPER_FLASH_DATA_FAILED 342
#define SN_READING_CE_IMAGE_HEADER      343
#define SN_INVALID_CE_HEADER_CRC        344
#define SN_READING_CE_HEADER_FAILED     345
#define SN_ERROR_ALLOCATING_MEM_CE_IMAGE 346
#define SN_READING_CE_IMAGE_DATA_FAILED 347
#define SN_INVALID_SPLASH_DATA_CRC      348
#define SN_INVALID_CE_DATA_CRC          349
#define SN_READING_MOTOR_CONTROLLER_HEADER 350
#define SN_SKIPPING_MOTOR_CONTROLLER_HEADER 351
#define SN_READING_MOTOR_CONTROLLER_HEADER_FAILED 352
#define SN_INVALID_MOTOR_CONTROLLER_HEADER_CRC 353
#define SN_UPDATING_MOTOR_CONTROLLER_PROGRAM_FLASH 354
#define SN_READING_MOTOR_CONTROLLER_PROGRAM_FLASH_FAILED 355
#define SN_WRITING_MOTOR_CONTROLLER_PROGRAM_FLASH_FAILED 356
#define SN_INVALED_MOTOR_CONTROLLER_PROGRAM_FLASH_CRC 357
#define SN_UPDATING_MOTOR_CONTROLLER_DATA_FLASH 358
#define SN_READING_MOTOR_CONTROLLER_DATA_FLASH_FAILED 359
#define SN_WRITING_MOTOR_CONTROLLER_DATA_FLASH_FAILED 360
#define SN_INVALID_MOTOR_CONTROLLER_DATA_FLASH_CRC 361
#define SN_READING_CE_IMAGE_DATA        362
#define SN_UPDATE_FAILED                363
#define SN_UPDATE_COMPLETE              364
#define SN_PLEASE_REMOVE_USB_DRIVE      365
#define SN_POWER_DOWN_SYSTEM            366
#define SN_UNKNOWN                      367
#define SN_UPDATE_SYSTEM_SOFTWARE       368
#define SN_TO                           369
#define SN_SYSTEM_SOFTWARE              370
#define SN_NO_CHANGE                    371
#define SN_UPDATE_MOTOR_CONTROLLER_SOFTWARE 372
#define SN_MOTOR_CONTROLLER_SOFTWARE    373
#define SN_FLASH_DATA_REPAIR            374
#define SN_CHECK_SERIAL_NUMBER          375
#define SN_SERIAL_NUMBER                376
#define SN_VERIFY_SERIAL_NUMBER         377
#define SN_ENTER_SERIAL_NUMBER          378
#define SN_SERIAL_NUMBER_INSTRUCTIONS   379
#define SN_CHANGE                       380
#define SN_CONTINUE                     381
#define SN_UPDATE_CANCELLED             382

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
